//cart types

export const ADD_ORDER_ITEM_SUCCESS = "ADD_ORDER_ITEM_SUCCESS";
export const REMOVE_ORDER_ITEM_SUCCESS = "REMOVE_ORDER_ITEM_SUCCESS";
export const DECREASE_QUANTITY_SUCCESS = "DECREASE_QUANTITY_SUCCESS";
export const INCREASE_QUANTITY_SUCCESS = "INCREASE_QUANTITY_SUCCESS";
export const EMPTY_CART_SUCCESS = "EMPTY_CART_SUCCESS";
export const GET_TOTAL_COST_SUCCESS = "GET_TOTAL_COST_SUCCESS";

//crud TYPES

export const LOAD_CHILIES_SUCCESS = "LOAD_CHILIES_SUCCESS";
export const LOAD_CHILIES_BY_ID_SUCCESS = "LOAD_CHILIES_BY_ID_SUCCESS";
export const CREATE_CHILI_SUCCESS = "CREATE_CHILI_SUCCESS";
export const UPDATE_CHILI_SUCCESS = "UPDATE_CHILI_SUCCESS";
export const DELETE_CHILI_SUCCESS = "DELETE_CHILI_SUCCESS";
